paths:
  /api/testing/all-data:
    delete:
      summary: Delete all data (testing utility)
      tags:
        - Testing
      responses:
        '204':
          description: No content. All data deleted